services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Cpsit\CpsitProposal\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Cpsit\CpsitProposal\Service\NotificationService:
    public: true

  Cpsit\CpsitProposal\Service\PageLinkService:
    public: true
